version: '3'

services:
  web:
    build: .
    command: ["uvicorn", "loonsTd.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"