# Generated by Django 4.2.7 on 2023-11-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameState', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='initial_coins',
            new_name='coins',
        ),
    ]
