# Generated by Django 4.2.7 on 2023-11-27 04:32

from django.db import migrations
from django.db import migrations

def create_initial_items(apps, schema_editor):
    Item = apps.get_model('gameState', 'Item')
    Item.objects.create(name='BasicTurret', cost=100)
    Item.objects.create(name='AdvancedTurret', cost=200)
    # Add more items as needed...

class Migration(migrations.Migration):

    dependencies = [
        ('gameState', '0002_rename_initial_coins_player_coins'),  # Replace with the name of the previous migration
    ]

    operations = [
        migrations.RunPython(create_initial_items),
    ]