# Generated by Django 4.2.7 on 2023-11-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameState', '0003_auto_20231126_2332'),
    ]

    operations = [
    ]
